project_id = "iovkqbsexontzywbapur"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_schemas = ["extensions", "auth", "realtime", "storage"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false
enable_signup = true
enable_confirmations = false
enable_recovery = true
double_confirm_changes = false

[functions.generate-content]
verify_jwt = true

[functions.handle-generation-callback]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

[functions.serve-asset]
verify_jwt = false