// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyocchycqimbwnaqxjfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b2NjaHljcWltYnduYXF4amZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNDk4NjQsImV4cCI6MjA3NTgyNTg2NH0.ffpUITiCzykgLXf99N-d3V6m9QPXhkHkvpE1ZyUZOIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});